version: "3"
services:
  mongo:
    container_name: mongo
    image: bitnami/mongodb:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
  bot:
    container_name: bot
    image: bot
    restart: always
    build: .
    links:
      - mongo
    depends_on:
      - mongo
    dns:
      - 8.8.8.8
      - 4.4.4.4
