version: "3"
services:
  bot:
    container_name: bot
    image: bot
    restart: always
    build: .
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'