version: "3"
services:
  mongo:
    container_name: mongo
    image: bitnami/mongodb:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'
    environment:
      - TZ=Ukraine/Kyiv
  bot:
    container_name: bot
    image: bot
    restart: always
    build: .
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - TZ=TZ=Ukraine/Kyiv