services:
  aicbot-mongo:
    container_name: aicbot-mongo
    image: bitnami/mongodb:latest
    restart: always
    env_file:
      - path: ./.env.production
        required: false
      - path: ./.env.development
        required: false
    volumes:
      - "aicbot-mongo-volume:/data/db"
    ports:
      - '27017:27017'
  aicbot:
    container_name: aicbot
    image: alexincube/aicotest:latest
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    #command: sleep infinity
    build: .
    env_file:
      - path: ./.env.production
        required: false
      - path: ./.env.development
        required: false
    volumes:
      - type: bind
        source: ./yt-cookies.json
        target: /bot/yt-cookies.json
        read_only: false
    links:
      - aicbot-mongo
    depends_on:
      - aicbot-mongo

volumes:
  aicbot-mongo-volume:
    external: true
