name: Bug Report
description: Bug report for anything
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please also ensure you have searched for any existing reports of this issue before you begin - if one exists, please leave a thumbs-up and/or a comment on that one, rather than knowingly filing a duplicate report, as duplicates just slow things down.
  
        Note that most fields are required to be filled-in before you can submit this report, as it is all essential information which we will require in order to confirm and fix your issue.

  - type: dropdown
    id: user-type
    attributes:
      label: Who are you? User (who just use bot from discord)/developer/admin (who download all bot stuff to host)?
      description: If you are on an older version, update and confirm your issue stil exists!
      multiple: true
      options:
        - User
        - Developer
        - Admin
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write a concise yet detailed description of the issue!)
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Add detailed, ordered steps for someone else to recreate the issue into the gaps below (add as many steps into the middle as you require)
      value: |
        1. Use command
        2. 
        3. 
        4. See the issue
    validations:
      required: true

  - type: dropdown
    id: repro-rate
    attributes:
      label: How reliably can you recreate this issue using your steps above?
      options:
        - Always
        - Most Times
        - Only Sometimes
        - Rarely
        - Only Ever Happened Once
    validations:
      required: true

  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
