blank_issues_enabled: false
contact_links:
  - name: Frequently Asked Questions
    url: https://github.com/AlexInCube/AICoTest/wiki/Frequently-Asked-Questions
    about: AICoTest Frequently Asked Questions

