name: Tests

on:
  push:
    branches: ['**']
    paths-ignore:
      - '**/wiki/**'
      - '/wiki/**'
      - 'docker-compose.yml'
      - '.env'
      - '*.sh'
  pull_request:
    branches: ['**']
    paths-ignore:
      - '**/wiki/**'
      - '/wiki/**'
      - 'docker-compose.yml'
      - '.env'
      - '*.sh'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SECRET_KEY: ${{ secrets.ENV_DEVELOPMENT }}
          file_name: .env.development
          fail_on_empty: true
          sort_keys: false
          directory: '${{ github.workspace }}/AlCoTest/AlCoTest'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm run test
