name: Tests

on:
  push:
    branches: ['**']
    paths-ignore:
      - '**/wiki/**'
      - '/wiki/**'
      - 'docker-compose.yml'
      - '.env'
      - '*.sh'
  pull_request:
    branches: ['**']
    paths-ignore:
      - '**/wiki/**'
      - '/wiki/**'
      - 'docker-compose.yml'
      - '.env'
      - '*.sh'

jobs:
  tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Make env file
        run: |
          pwd
          touch .env.development
          echo '${{ secrets.ENV_DEVELOPMENT }}' > .env.development

      - name: Make yt-cookies.json
        run: |
          touch yt-cookies.json
          echo '${{ secrets.YOUTUBE_COOKIES }}' > yt-cookies.json

      - name: Run tests
        run: pnpm run test
